name: Auto Sync to GitLab

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 拉取完整历史
          ref: master # 明确检出 main 分支

      - name: Check local branches (debug)
        run: |
          git branch -a
          git log --oneline

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "actions@github.com"

      - name: Push to GitLab
        run: |
          if ! git remote | grep -q "gitlab"; then
            git remote add gitlab http://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@1.95.34.168:8099/renfuxing/power.git
          fi
          # 推送当前分支（自动匹配远程）
          git push gitlab HEAD
